services:
  api:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PORT=${PORT}      
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
      db-test:
        condition: service_healthy

  db:
    image: postgres:17.2
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
#    volumes:
#      - 
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5    